version: '3.3'
services:
  webui:
    build: 'WebUi/'
    ports: 
      - '80:80'
    depends_on:
      - monitorapp
  monitorapp:
    build: 'MonitorApp/'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://database:3306/housing_monitor'
      SPRING_DATASOURCE_USERNAME: 'monitor'
      SPRING_DATASOURCE_PASSWORD: 'rVcfuNyKXKQW'
      DATADOWNLOADER_URL: 'http://datadownloader'
    depends_on:
      - database
      - datadownloader
  datadownloader:
    build: 'DataDownloader/'
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'housing_monitor'
      MYSQL_USER: 'monitor'
      MYSQL_PASSWORD: 'rVcfuNyKXKQW'
      MYSQL_ROOT_PASSWORD: 'quxPvpjkdQS6'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dbdata:/var/lib/mysql
      - ./Database:/docker-entrypoint-initdb.d
volumes:
  dbdata:
